#!/usr/bin/env python3
"""Embed an HTML control panel into the firmware so the robot serves it.
    python tools/embed_panel.py web/control-panel.html          # writes firmware/control-panel.h
    python tools/embed_panel.py web/control-panel.html --check  # exit 1 if the header is stale
The page is stored in flash as one raw string (`panel_html`). The robot has no internet, so the page
must not load anything from the web: this tool warns about external links, which will not work.
"""
from __future__ import annotations
import argparse
import re
import sys
from pathlib import Path
from typing import Optional, Sequence
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = REPO_ROOT / "firmware" / "control-panel.h"
DELIMITER = "nova_panel"
SIZE_WARN_BYTES = 80_000
HEADER_TEMPLATE = """// GENERATED by tools/embed_panel.py from {source}. Do not edit by hand.
#ifndef CONTROL_PANEL_H
#define CONTROL_PANEL_H
#include <pgmspace.h>
const char panel_html[] PROGMEM = R"{delim}({html}){delim}";
#endif
"""
EXTERNAL_PATTERN = re.compile(
    r"""(?:src|href)\s*=\s*["'](?:https?:)?//|@import\s+(?:url\()?["']?(?:https?:)?//|url\(\s*["']?(?:https?:)?//""",
    re.IGNORECASE,
)
class EmbedError(Exception):
    """A problem with the input the user can fix."""
def external_references(html: str) -> list[str]:
    """Return the snippets of html that load something from the internet."""
    return [m.group(0).strip() for m in EXTERNAL_PATTERN.finditer(html)]
def render_header(html: str, source: str) -> str:
    if f"){DELIMITER}\"" in html:
        raise EmbedError(f"the page contains the reserved text ){DELIMITER}\"; remove or change it")
    if not html.strip():
        raise EmbedError("the HTML file is empty")
    return HEADER_TEMPLATE.format(source=source, delim=DELIMITER, html=html)
def normalise(text: str) -> str:
    """Use LF line endings so the header is the same on every OS."""
    return text.replace("\r\n", "\n").replace("\r", "\n")
def read_source(path: Path) -> str:
    try:
        return normalise(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError) as err:
        raise EmbedError(f"cannot read {path}: {err}") from err
def source_label(path: Path) -> str:
    try:
        return path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.name
def build(source: Path, out: Path, *, check: bool) -> int:
    html = read_source(source)
    header = render_header(html, source_label(source))
    for ref in external_references(html):
        print(f"warning: external link will not load on the robot's offline network: {ref}", file=sys.stderr)
    size = len(html.encode("utf-8"))
    if size > SIZE_WARN_BYTES:
        print(f"warning: page is {size} bytes; flash is nearly full, consider minifying", file=sys.stderr)
    if check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if normalise(current) != header:
            print(f"{out} is out of date; run: python tools/embed_panel.py {source_label(source)}", file=sys.stderr)
            return 1
        print(f"{out.name} is up to date ({size} bytes of HTML)")
        return 0
    out.write_text(header, encoding="utf-8", newline="\n")
    print(f"wrote {out} ({size} bytes of HTML)")
    return 0
def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument("source", type=Path, help="the control panel .html file")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="header to write (default firmware/control-panel.h)")
    parser.add_argument("--check", action="store_true", help="do not write; exit 1 if the header is stale")
    args = parser.parse_args(argv)
    try:
        return build(args.source, args.out, check=args.check)
    except EmbedError as err:
        print(f"error: {err}", file=sys.stderr)
        return 1
if __name__ == "__main__":
    sys.exit(main())