#ifndef CONTROL_PANEL_H
#define CONTROL_PANEL_H
#include <pgmspace.h>
const char panel_html[] PROGMEM = R"nova_panel(<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Rover Nova</title>
<style>
body { max-width: 430px; margin: 0 auto; padding: 8px; }
.grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 4px; }
#places { grid-template-columns: 1fr 1fr; }
#screen { width: 100%; image-rendering: pixelated; }
button { min-height: 48px; font-size: 16px; }
button.on { font-weight: bold; }
#pad { grid-template-columns: repeat(3, min(28vw, 110px)); justify-content: center; gap: 8px; }
#pad button { aspect-ratio: 1; font-size: 40px; padding: 0; }
#pad button[data-stop] { font-size: 18px; font-weight: bold; }
.row { margin: 8px 0; }
select { min-height: 48px; font-size: 16px; }
[data-go] { touch-action: none; -webkit-user-select: none; user-select: none; -webkit-touch-callout: none; }
</style>
</head>
<body>
<h1>Rover Nova</h1>
<p id="link" hidden>Not connected. Join the Nova-Controller Wi-Fi.</p>
<h2>My place in space:</h2>
<canvas id="screen" width="128" height="64"></canvas>
<div class="grid" id="places"></div>
<p><button id="halt">Stop</button></p>
<h2>Drive</h2>
<p>Hold a button to move. Let go to stop.</p>
<div class="grid" id="pad">
  <span></span><button data-go="forward" aria-label="Forward">&uarr;</button><span></span>
  <button data-go="left" aria-label="Left">&larr;</button><button data-stop>STOP</button><button data-go="right" aria-label="Right">&rarr;</button>
  <span></span><button data-go="backward" aria-label="Back">&darr;</button><span></span>
</div>
<h2>Poses</h2>
<div class="grid" id="poses"></div>
<details>
  <summary><h2 style="display:inline">Tuning</h2></summary>
  <div class="row"><span>Frame delay</span><span class="step" data-key="frameDelay" data-min="10" data-max="1000" data-inc="10"><button>-</button> <output>100</output> <button>+</button></span></div>
  <div class="row"><span>Walk cycles</span><span class="step" data-key="walkCycles" data-min="1" data-max="50"><button>-</button> <output>10</output> <button>+</button></span></div>
  <div class="row"><span>Motor delay</span><span class="step" data-key="motorCurrentDelay" data-min="20" data-max="200" data-inc="5"><button>-</button> <output>40</output> <button>+</button></span></div>
  <div class="row"><span>Face fps</span><span class="step" data-key="faceFps" data-min="1" data-max="30"><button>-</button> <output>8</output> <button>+</button></span></div>
  <div class="row"><span>Slow motion (1 = full speed)</span><span class="step" data-key="slowFactor" data-min="1" data-max="10"><button>-</button> <output>5</output> <button>+</button></span></div>
</details>
<details id="calib">
  <summary><h2 style="display:inline">Calibration</h2></summary>
  <p>Do this with the robot on a stand. It is saved on the robot and kept after power-off.</p>
  <ol>
    <li>Press Start. Every joint goes to the middle.</li>
    <li>Pick a joint.</li>
    <li>Move it with the buttons as far as it can safely go one way, then press Set min. Move it the other way and press Set max. Stop before it pushes on anything.</li>
    <li>Move it to where it should sit at rest (hip parallel to the body) and press Set centre.</li>
    <li>Repeat for each joint.</li>
  </ol>
  <p><button id="calib-start">Start</button></p>
  <div class="row"><select id="calib-joint"></select></div>
  <div class="grid" style="grid-template-columns: repeat(4, 1fr)">
    <button data-calib-jog="-10">-10</button><button data-calib-jog="-1">-1</button><button data-calib-jog="1">+1</button><button data-calib-jog="10">+10</button>
  </div>
  <p id="calib-info">Press Start.</p>
  <div class="grid">
    <button data-calib-set="min">Set min</button><button data-calib-set="center">Set centre</button><button data-calib-set="max">Set max</button>
  </div>
  <p>If a joint turns the wrong way in a pose, reverse it.</p>
  <div class="grid" style="grid-template-columns: 1fr 1fr">
    <button data-calib-set="reverse">Reverse this joint</button><button id="calib-reverse-all">Reverse all joints</button>
  </div>
  <p><button id="calib-reset">Reset this joint</button></p>
</details>
<p><a id="classic" href="/classic">Wi-Fi setup</a></p>
<details id="debug">
  <summary><h2 style="display:inline">Debug</h2></summary>
  <p>Move one joint by 10 degrees. The calibrated limits apply.</p>
  <div class="row"><select id="debug-joint"></select></div>
  <div class="grid" style="grid-template-columns: 1fr 1fr">
    <button data-debug-jog="-10">-10</button><button data-debug-jog="10">+10</button>
  </div>
  <p id="debug-info"></p>
</details>
<script>
const FACES = {"walk":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAAAAAAAAAAAAPAAPAAAAAAAAAAAAAAAAAB4AHwAAAHgAAAAAAAeAAAAfAB4AAAAcAAAAAAAMAAAADwA+AAAABwAAAAAAGAAAAA+APAAAAAAAAAAAABAAAAAHgHwAAAPgAAAAAAAA+AAAB8B8AAAH8AAAAAAAAfwAAAfAeAAAD/gAAAAAAAP+AAADwHgAAA/4AAAAAAAD/gAAA8D4AAAP+AAAAAAAA/4AAAPA+AAAD/gAAAAAAAP+AAAD4PgAAA/4AAAAAAAD/gAAA+D4AAAP+AAAAAAAA/4AAAPg+AAAB/AAAAAAAAH8AAAD4PgAAAPgAAAAAAAA+AAAA+D4AAAAAAAAAAAAAAAAAAPg+AAAAAAAAAAAAAAAAAAD4PgAAAAAAAAAAAAAAAAAA8B4AAAAAAAAf4AAAAAAAAPAfAAAAAAAAP/AAAAAAAAHwHwAAAAAAAB/wAAAAAAAB8A8AAAAAAAAAAAAAAAAAAeAPgAAAAAAAAAAAAAAAAAPgD4AAAAAAAAAAAAAAAAADwAfAAAAAAAAAAAAAAAAAB8ADwAAAAAAAAAAAAAAAAAeAA+AAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","rest":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAGAAAAAAAAABwAAAAAAAAABwAAAAAAAAA8AAAAAAAAAAeAAAAAAAAAeAAAAAAAAAADwAAAAAAAAHAAAAAAAAAAAcAAAAAAAADwAAAAAAAAAADgH8AAAAAA4AAAAAAAAAAA4B+AAAAAAeAAAAAAAAAAAPAHgAAAAAHAAAAAAAAAAABwBwAAAAABwAAAAAAAAAAAcA4AAAAAAcAAAAAAAAAAAHgcAAAAAAPAAAAAAAAAAAB4P4AAAAADwAAAAAAAAAAAeD+AAAAAA8AAAAAAAAAAAHgAAAAAAAPAAAAAAAAAAAB4AAAAAAADwA8A8AAA4B4AeAAAAAAAA8APAPAAAOAeAHgAAAAAAAPABwDwAADwHgB4AAAAAAABwAeB4AAA8BwAeAAAAAAAAcAHw+AAAHg8AHgAAAAAAAHAA//AAAB/+ABwAAAAAAAB4AH/gAAAP/AA8AAAAAAAAOAAfgAAAA/gAPAAAAAAAADgAAAAAAAAAADgAAAAAAAAcAAAAA4AAAAB4AAAAAAAAHAAAAAbAAAAAcAAAAAAAAA4AAAAGwAAAAOAAAAAAAAAHAAAAB4AAAAHAAAAAAAAAAwAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","swim":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAgAAAAAAGAQAAAAAAAeAAAcAAAAAABgPAAAAAAAPAAADhwAHAAAcBwAAAAAADgAAAYcABwAADAOAAAAAABwAAAOGAAMAAAwBwAAAAAAcAAADj///gAAcAcAAAAAAOAH//w///4//+AHgAAAAADgB//4OAAOP//AA4AAAAAB4AHw8DgADgeHgAPAAAAAAcABwDg4AA4OAcADwAAAAAHAA4AcOAAOHADgAcAAAAABwAcADDgADhgAcAHAPgAAAcAHAA4YAAw4AHABwH+HAAHABg4OHAAcMDgwAcB/xwABwAYPBhwAHDB4MAHA4/8AAcAGDgYcABwwODABwOD+AAHABgAGHgA4MAAwAcAAfAABwAcADg4AODgAcAHAAAAAAcAHAAwPAHAYAHABwAAAAAHAA4AcB4DwHADgA8AAAAAB4AHAOAPj4A4BwAPAAAAAAeAB8PAB/8AHh4ADgAAAAADgAH/gAH8AA/8AA4AAAAAA8AA/gAAAAAD+AAeAAAAAAHAAAAAAAAAAAAAHAAAAAAB4AAAAAAAAAAAADwAAAAAAOAAAAAAAAAAAAB4AAAAAABwAAAAAAAAAAAA8AAAAAAAMAAAAAAAAAAAAGAAAAAAABAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","dance":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAwAAAAAeAAAAAAAAAAAAAAOAAAAAPAHDgAAAADhwAAADwAAAADgA54AAAAA84AAAAcAAAABwAP8AAAAAH+AAAADgAAAAcAB+AAAAAA/AAAAA8AAAAOAAAAAAAAAAAAAAAHAAAADgAAAAAAAAAAAAAAB4AAAB4AAAAA/8AAAAAAAAeAAAAcAAAAAH/AAAAAAAADgAAAHAAAAAB/gAAAAAAAA4PwABwAAAAAP4AAAAPgAAPH+DgcAAAAAD8AAAAH+HADx/xwHAAAAAAfAAAAB/xwA88f8BwAAAAAHgAAAA4/8APOD/AcAAAAAA4AAAAOD+ADwAfAHAAAAAAMAAAAAAfAA8AAABwAAAAAAAAAAAAAAAPAAAAcAAAAAAAAAAAAAAADgAAAHAAAAAAAAAAAAAAAA4AAAB4AAAAAAAAAAAAAAAOAAAAeAAAAAAAAAAAAAAAHgAAADgAAAAAAAAAAAAAABwAAAA8AAAAAAAAAAAAAAAcAAAAHAAAAAAAAAAAAAAAOAAAAB4AAAAAAAAAAAAAAHgAAAAOAAAAAAAAAAAAAABwAAAABwAAAAAAAAAAAAAA4AAAAAMAAAAAAAAAAAAAAMAAAAABAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","wave":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAEAAAAAcAAAAAAAAAAAAAADwAAAAPAAAAAA///gAAAAAcAAAAHgAAAAAP//4AAAAADgAAABwAAAAADAAGAAAAAAcAAAA8AAAAABwABwAAAAAHAAAAOAAAAAAcAAcAAAAAB4AAAHgAACAAHAAHAAEAAAOAAABwAAA8ABwABwAHAAADwAAAcAAAPwAcAAcAPwAAA8AAAHAAAD/AHAAHAP8AAAHAAADwAAAP+BwABwP+AAABwAAA8AAAAf4MAAYP8AAAAcAAAPADuAA+DgAOH4AO4AHAAADwA5gAPg4ADh+ADmABwAAA8AHcAf4OAA4P8AdwAcAAAPAAzg/4DwAcA/wDOAHAAADwAOY/wAcAHAD/A5gBwAAAcAAAPwAHgDgAPwAAAcAAAHAAADwAA8B4AAcAAAPAAABwAAAgAAHx8AABAAADwAAAeAAAAAAA/+AAAAAAA4AAADgAAAAAAD+AAAAAAAOAAAA4AAAAAAAAAAAAAAAHgAAAHAAAAAAAAAAAAAAABwAAABwAAAAAAAAAAAAAAA8AAAAOAAAAAAAAAAAAAAAeAAAABwAAAAAAAAAAAAAAPAAAAAMAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","point":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgAAABAAAAAAAAAAAAADAC0AAAAwAAAHAAAAHAAAAYAhAAAAYAAABgAAAAwAAAHAIQAAAOAAAAwAhCAGAAAAwAAAAADAAAAAAIQgAAAAAGASAAABwAGAAACEIAAAOABgAAAAAYABgAAAhCAAADgAcAAAAAGAAYAAAI4gAAA4ADAAAAADgBGIAADKQAADEYAwAAAAA4A//AAAMYAAA/+AMAAAAAOAH/wAAAAAAAP/gDgAAAADgAPAAAAAAAAAOAA4AAAAAwADwAAAAAAAAHwAOAAAAAOABuAAAAAAAADsADgAAAADgA5wAAAAAAAAxgAwAAAAA4AMMAAAAAAAAccAMAAAAAOAACAAAAAAAAAAADAAAAABgAAAAAAAAAAAAABwAAAAAcAAAAAAAAAAAAAAcAAAAADAAAAAAAAAAAAAAGAAAAAAwAAAAAAAAAAAAADgAAAAAGAAAAAAAAAAAAAAwAAAAABwAAAAAAAAAAAAAYAAAAAAOAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","cute":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAAAAAAAAHwAAB4AAAAAAAAAAAAAAAA8AAA+AAAAAAAAAAAAAAAAHgAAPAAAAAAAAAAAAAAAAB8AAHwAAMAAAAAAAAABgAAPAAB4AAD4AAAAAAAAD4AAD4AA+AAA/gAAAAAAAD+AAA+AAPgAAH/AAAAAAAD/AAAHgADwAAAP8AAAAAAH/AAAB4AA8AAAA/wAAAAAH+AAAAfAAfAAAAD/AAAAAH+AAAAHwAHwAAAAPx////5+AAAAB8AB8A88AD8f///+fgADzwfAAfAfeAD/AA8APH+AB54DwAHwHngD/AAHgDwf4A88A8AB8DzwD/AAA8B4B/wPOAfAAfB54H/AAAHg8AD/HngHwAHwAAD+AAAB/+AAP4AAB8AB8AAA+AAAAH/AAA+AAAfAAPAAAOAAAAAAAAABgAAHgAD4AAAAAAAAAAAAAAAAB4AA+AAAAAAAAAAAAAAAAA+AAHgAAAAAAAAAAAAAAAAPgAB8AAAAAAAAAAAAAAAADwAAfAAAAAAAAAAAAAAAAB8AAD4AAAAAAAAAAAAAAAAeAAAeAAAAAAAAAAAAAAAAPAAAHwAAAAAAAAAAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","pushup":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAAAAAAAAAAHwAAAeAAAAAAAAAAAAAAAA8AAAPgAAAAAAAAAAAAAAAHgAADwAAAAAAAAAAAAAAAB8AAB8AADAAAAAAAAABgAAPAAAeAAA+AAAAAAAAD4AAD4AAPgAAP4AAAAAAAD+AAA+AAD4AAB/wAAAAAAD/AAAHgAA8AAAD/AAAAHAH/AAAB4AAPAAAAP8AAADwH+AAAAfAAHwAAAA/wAAB4H+AAAAHwAB8AAAAD8AAA8B+AAAAB8AAfAPPAA/B//+AfgADzwfAAHwH3gA/wf//AH+AB54DwAB8B54A/wH//4Af4A88A8AAfA88A/wAAAPAB/wPOAfAAHweeB/wAAABwAD/HngHwAB8AAA/gAAAAOAAP4AAB8AAfAAAPgAAAABwAA+AAAfAADwAADgAAAAAAAABgAAHgAA+AAAAAAAAAAAAAAAAB4AAPgAAAAAAAAAAAAAAAA+AAB4AAAAAAAAAAAAAAAAPgAAfAAAAAAAAAAAAAAAADwAAHwAAAAAAAAAAAAAAAB8AAA+AAAAAAAAAAAAAAAAeAAAHgAAAAAAAAAAAAAAAPAAAB8AAAAAAAAAAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","freaky":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAAAAAAAAAAHgAAAeAAAAAAAAAAAAAAAA8AAAPgAAAAAAAAAAAAAAAPgAADwAAAAAAAAAAAAAAAB4AAB8AAAAAAAAAAAAAAAAfAAAeAAAAAAAAAAAAAAAADwAAPgAAAAAAAAAAAAAAAA+AAD4AAAAAAAAAAAAAAAAPgAA8AAAAAAAAAAAAAAAAB4AAPAAAAAAAAAAAAAAAAAeAAHwAAAAf/+AAAH//gAAHgAB8AAAAH//gAAB//4AAB8AAfB98AB//4AAAf/+eeAfAAHwPPAAf/+AAAH//n3wHwAB8B54AAAHnwH4AB488B8AAfAPPAAAB58B+AAeHngfAAHwBzwAAAefAfgAHg88HwAB8AAAAAAHn4HwAB4AAB8AAfAAAAAAB4/H8AAeAAAeAADwAAAAAAAP/+AAAAAAHgAA+AAAAAAAB//AAAAAAD4AAPgAAAAAAAP/gAAAAAA+AAB4AAAAAAAA/wAAAAAAPAAAfAAAAAAAAAAAAAAAAHwAAHwAAAAAAAAAAAAAAAB4AAA+AAAAAAAAAAAAAAAA+AAAHgAAAAAAAAAAAAAAAPAAAB8AAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","bow":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAAA/AAAAAAAAAA+AAA+AAAAAH4AAAB4AAAAPAAAfAAAAAAfAAAAPAAAAHwAAPgAAAAAD4AAAD4AAAB4AAHgAAAAAAfAAAAeAAAA+AAAAAAAAAAAAAAAHwAAAPAAAAAAAAAAAAAAAA8AAAHwAAAfAAAAAAH4AAAPgAAB8AAAP4AAAAAD/AAAD4AAAeAAAH/AAAAAA/wAAAeAAAHgAAB/wAAAAAf+AAAHgAAD4AAAf8AAAAAH/gAAB4AAA+AAAH/AADwAB/4AAAfAAAPgAAB/wAB/AAf+AAAHwAAD4AAAP8AB/4AD/AAAB8AAA+AAAD+AB//gA/wAAAfAAAPgAAAfAB/D+AH4AAAHwAAD4AAAAAB/AP4AAAAAB8AAA+AfAAAB/AA/gAAPAAfAAAPgP4AAA/AAD8AAP8AHgAAB4HHAAAPAAAPAADnAB4AAAfBgwAABAAABgABw4A+AAAHwYMAAAAAAAAAAYOAPgAAA8GDAAAAAAAAAAHDgDwAAAPhxwAAAAAAAAAA5wB8AAAD4P4AAAAAAAAAAP8AeAAAAfB8AAAAAAAAAAB8APgAAADwAAAAAAAAAAAAAADwAAAA+AAAAAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","worm":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAADwAAAeAAAAAAAAAAAAAAAAeAAAPgAAAAAAAAAAAAAAAHwAADwAAAYAAP//AABgAAA8AAB8AAAHgAD//wAB4AAAPgAAeAAAB+AA//8AB+AAAD4AAPgAAAf4APAPAB/gAAAeAAD4AAAB/gDwDwB/gAAAHwAA+AAAAH+A8A8B/gAAAB8AAPAAAAAf4PAPB/gAAAAPAADwAAAAB/jwDx/gAAAADwAA8AAAAAH48A8fgAAAAA8AAfAAAAAH+PAOH+AAAAAPAAHwAAAAP+AAHg/4AAAADwAB8AAAAP+AAB4B/wAAAA8AAfAAAAP+AAAeAH/AAAAPAADwAAAH+AAAPAAf4AAADwAA8AAAB8AAADwAB+AAAA8AAPAAAAcAAAB8AADgAAAPAAD4D4fEAAAA+AAAIfD4HwAA+B8HwAAAAfAAAAPg+B8AAPgfD4AAAAfgAAAD4fAeAAB4Hw+AAAAfwAAAA+HwPgAAfB4PgAAAD4AAAAPB8D4AADweDwAAAAYAAAADweA8AAA+Pg8AAAAAAAAAB8HgfAAAHjweAAAAAAAAAAeDwHgAAA8AAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","shake":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAAAAAAAAAAfAAAAPAAAAAAAAAAAAAAADwAAAHwAAAAAAAAAAAAAAAeAAAB4AAAAAAAAAAAAAAAHwAAA+AAAAAAAAAAAAAAAA8AAAPAAAAAAAAAAAAAAAAPgAAHwAAAAAAAAAAAAAAAD4AAB8AAAAAAAAAAAAAAAAeAAAeAAAAAAAAAAAAAAAAHgAAHgAAAAAAAAAAAAAAAB8AAD4AAP//AAAAAB//4AAfAAA+AAD//wAAAAAf/+AAHwAAPgAA//4AAAAAH//gAB8AAD4AAA7wAAAAAAHOAAAPAAA+AAAO8AOA4HAB3gAADwAAPgAA//8DgOBwH//gAB8AAD4AAP//A4DgcB//4AAfAAA+AAAAAAOA4HAAAAAAHwAAPgAAAAADweBwAAAAAB8AAB4AAAAAAcHwcAAAAAAeAAAfAAAAAAHj8PAAAAAAHgAAHwAAAAAA///gAAAAAD4AAA8AAAAAAH8fwAAAAAA+AAAPgAAAAAAAAAAAAAAAPAAAD4AAAAAAAAAAAAAAAHwAAAfAAAAAAAAAAAAAAAB4AAADwAAAAAAAAAAAAAAA8AAAA+AAAAAAAAAAAAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","shrug":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAPgAADwAAAAAAAAAAAAAAAB4AAB8AAAAAAAAAAAAAAAAPAAAeAAAAAAAAAAAAAAAAD4AAPgAAAAAAAAAAAAAAAAeAADwAAAAAAAAAAAAAAAAHwAB8AAAAAAAAAAAAAAAAB8AAfDxwAAAAAAAAAAAAAAPAAHg+8AAAAAAAAAAAAAADwAB4H/AAAAAAAAAAAAAAA+AA+B/gAAAAAAAAAAAAAAPgAPgPwAAAAAAAAAAAAAAD4AD4AAAAAAAAAAAAAAAAA+AA+AAD////8AAAP////wHgAPgAA/////PgHz////8B4AD4AAP////z8B8/////A+AA+AAB////8/A/H////wPgAPgAAAAAAAHwPwAAAAAD4AD4AAAAAAAB/H4AAAAAA+AAeAAAAAAAAP/+AAAAAAPAAHwAAAAAAAD//AAAAAADwAB8AAAAAAAAP/gAAAAAB8AAPAAAAAAAAB/gAAAAAAfAAD4AAAAAAAAAAAAAAAAHgAA+AAAAAAAAAAAAAAAAD4AAHwAAAAAAAAAAAAAAAA8AAA8AAAAAAAAAAAAAAAAeAAAPgAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","dead":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAAAAAAAADwAAAAAeAAAAAAAAAAAAAAeAAAAAPgAAAAAAAAAAAAAHwAAAADwAAAAAAAAAAAAAA8AAAAB8AAAAAAAAAAAAAAPgAAAAeAAAAAAAAAAAAAAD4AAAAPgAAAAAAAAAAAAAAeAAAAD4AAAAAAAAAAAAAAHwAAAA8AAAAAAAAAAAAAAB8AAAAPAAAAAAAAAAAAAAAPAAAAHwAAAAAAAAAAAAAADwAAAB8AAAAAAAAAAAAAAA8AAAAfAAAAAAAAAAAAAAAPAAAAHwAAAAAAAAAAAAAADwAAAB8AB//+AAAAB//+AA8AAAAfAAf//gAAAAf//gAPAAAAHwAAO8AAAAAAPcAADwAAAB8AADvAAAAAAD3AAA8AAAAfAAA7wAAAAAA9wAAPAAAADwAAO8AAAAAAPcAAHwAAAA+AAAAAAAAAAAAAAB8AAAAPgAAAAAAAAAAAAAAeAAAAB4AAAAD48fHwAAAAPgAAAAfAAAAD/////AAAAD4AAAAHwAAAA5+fnzwAAAA8AAAAA+AAAAAAAAAAAAAAfAAAAAHgAAAAAAAAAAAAAHgAAAAB8AAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","crab":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfAAAAAAA///8AAAAAPAAAHgAAAAAAP///AAAAAB4AAD4AAAAAAD///wAAAAAfAAA8AAAEAAA///8AAAgADwAAfAAAB4AAPgAfAAA4AA+AAHgAAAfgAD4AHwAB+AAPgAD4AAAB/AA+AB8AD/AAB4AA+AAAAH+APgAfAD+AAAfAAPAAAAAP4D4AHwH+AAAHwADwAAAAA/g+AB8H8AAAA8AB8AAAAAf4PgAfA/gAAAPAAfAAAAAfwD4AHwD/AAADwAHwAAAA/wA+AB8AH8AAA8AB8AAAA/gAPwA/AAf4AAPAAfAAAAfAAD8APwAA+AADwAHwAAAHAAAfAD4AABgAA8AB8AAAAAAAH4B+AAAAAAPAAfAAAAf/+B/A/gf/+AADwAHwAAAH//gP4fwH//gAA8AA8AAAAAAAB//4AAAAAAfAAPgAAAAAAAP/8AAAAAAHwAD4AAAAAAAB/+AAAAAAB4AAeAAAB//4AH+AB//4AA+AAHwAAAf/+AAAAAf/+AAPgAB8AAAAAAAAAAAAAAAADwAAPgAAAAAAAAAAAAAAAB8AAB4AAAAAAAAAAAAAAAAeAAAfAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","idle":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAAAAAAAAAAAAPAAPAAAAAAAAAAAAAAAAAB4AHwAAAAAAAAAAAAAAAAAfAB4AAA8AAAAAAAAADwAADwA+AAAAAAAAAAAAAAAAAA+APAAAAAAAAAAAAAAAAAAHgHwAAAPgAAAAAAAA+AAAB8B8AAAH8AAAAAAAAfwAAAfAeAAAD/gAAAAAAAP+AAADwHgAAA/4AAAAAAAD/gAAA8D4AAAP+AAAAAAAA/4AAAPA+AAAD/gAAAAAAAP+AAAD4PgAAA/4AAAAAAAD/gAAA+D4AAAP+AAAAAAAA/4AAAPg+AAAB/AAOA4HAAH8AAAD4PgAAAPgADgOBwAA+AAAA+D4AAAAAAA4DgcAAAAAAAPg+AAAAAAAOA4HAAAAAAAD4PgAAAAAADweBwAAAAAAA8B4AAAAAAAcHwcAAAAAAAPAfAAAAAAAHj8PAAAAAAAHwHwAAAAAAA///gAAAAAAB8A8AAAAAAAH8fwAAAAAAAeAPgAAAAAAAAAAAAAAAAAPgD4AAAAAAAAAAAAAAAAADwAfAAAAAAAAAAAAAAAAAB8ADwAAAAAAAAAAAAAAAAAeAA+AAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="};
const EARTH_MAP = bytes('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/B//4AAAAAAAAAAAAAAAH+B//+AAAAAAAAAAAAAAAH8AB//gAAAAAH+AAAAAAAAADgP/4AAAAD///gAAAH//B//B/4AA/gH//////8P////38fgAA/w////////B////+cDgAAf/////////gP///8OAAAAP/////////gBgP/+D8AAAg///////8HAAAB//8/gAAMf//////+BgAAAP///8AAN////////gQAAAB///+AAAf///////8AAAAAP///AAAH///////+AAAAAD///AAAB38Of////AAAAAA///AAABwf/n////EAAAAAP//gAAAYAf9///8RAAAAAB//4AAAD8Af////kwAAAAAP/8AAAB/gP////4gAAAAAA/2AAAA///7///+AAAAAAAPwQAAAf//fP///gAAAAAAB8AAAAH///8P//gAAAAAAAPAgAAD//+/g+fgAAAAAAAA+AAAA////gPHwAAAAAAAADgAAAP///wDgcEAAAAAAAAEAAAD///gAQHhAAAAAAAAAn4AAf///AEBQQAAAAAAAAB/AAD///gAAQAAAAAAAAAA/8AAQf/4AAAMAAAAAAAAAP/AAAH/8AAAHAAAAAAAAAH/8AAB/+AAARwAAAAAAAAB//4AAP/AAAAADgAAAAAAAP//AAD/wAAAIAcAAAAAAAD//gAAf8AAAAAAAAAAAAAAf/4AAP/AAAAAMgAAAAAAAD/8AAD/zAAAAH4AAAAAAAAf/AAA/8wAAAH/AAAAAAAAH/wAAH+IAAAH/4AAAAAAAB/wAAB/CAAAB//AAAAAAAAf4AAAPwAAAAf/wAAAAAAAP8AAAD4AAAAH/8AAAAAAAD/AAAAcAAAAB7/AAAAAAAA/gAAAAAAAAAAPgEAAAAAAPgAAAAAAAAAAAwBgAAAAADwAAAAAAAAAAAAAQAAAAAA4AAAAAAAAAAAAAIAAAAAAOAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAeAAAAAAAAAAAAAAAAAAAAP4AAAP///////gAAAAAH///gH//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////w==');
const MOON_SRC = bytes('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAA////AAAAAAAAAAAAAAAAAAAAAAAD///////AAAAAAAAAAAAAAAAAAAAAA///////wAAAAAAAAAAAAAAAAAAAAP/M//////8AAAAAAAAAAAAAAAAAAAD/zP//////AAAAAAAAAAAAAAAAAAA/8zMz///Mz/wAAAAAAAAAAAAAAAAAP/MzM///zM/8AAAAAAAAAAAAAAAAA/zMzMzPMzMzP8AAAAAAAAAAAAAAAAP8zMzMzzMzMz/AAAAAAAAAAAAAAAA/8zP/Mz/8zMzP/AAAAAAAAAAAAAAAP/Mz/zM//MzMz/wAAAAAAAAAAAAAA/z8zMzMzzMzMzM/wAAAAAAAAAAAAAf8/MzMzM8zMzMzP8AAAAAAAAAAAAAP8zM/MzMAAMzMzP/wAAAAAAAAAAAAD/MzPzMzAADMzMz/8AAAAAAAAAAAAD/M/8zMAAAAPzPz//wAAAAAAAAAAAB/zP/MzAAAAD8z8//8AAAAAAAAAAAD/DMzMzMwAADM/MA/z8AAAAAAAAAAB/gzMzMzMAAAzPzAP8/gAAAAAAAAAB+Az8zMzMwAzDMzMA//+AAAAAAAAAAfgM/MzMzMAMwzMzAP//gAAAAAAAAAPyIzMzAz8zMzzMzMD878AAAAAAAAAH4iMzMwM/MzM8zMzA/EfgAAAAAAAAHgjMzMAP//zAz/MzMz8R+AAAAAAAAB4IzMzAD//8wM/zMzM/EfgAAAAAAAB4IiMwAP/8ADAzzMz//8R+AAAAAAAAeGIjMAD//AAwM8zM///EfgAAAAAAAeAIAAA//8AADM/zM/878Z+AAAAAAAHgCAAAP//AAAzP8zP/M/GfgAAAAAAGAAAADPzPAzAAMz//zP/EZ+AAAAAABgAAAAz8zwMwADM//8z/xGfgAAAAAAZgAAMz8zMMwAAAzM/zO/Gf4AAAAAAGYAADM/MzDMAAAMzP8zPxn+AAAAAAGYAAAMzMzAADAAAzPMzE/Ef4AAAAABmAAADMzMwAAwAAMzzMxHxn+AAAAABgAAADP/MAAAAADPz/MzM5mf4AAAAAYAAAAz/zAAAAAAz8/zMzEZn+AAAAAYAAAAz8wAAAAAMzP/AMxHxH/4AAAAGAAAAM/MAAAAADMz/wDMR8Z/+AAAABgAAAAzMwAAAADMzMwAMwOfn/gAAAAYAAAAMzMAAAAAzMzMADMBH5/4AAAAYAAAAAzMAAAAAzMz/AAABH5n/gAAAGAAAAAMzAAAAAMzM/wAAAR+Z/4AAABgAAIgMwMAAAAADMzwAAAPP//+AAAAYAAGIDMDAAAAAAzM8AAADx///gAAAYCACIAADIAAAAAAMzAAAB//7/8AAAGBgBiAAAzAAAAAADMwAAA//+f/gAABgGAiIAAAAAAAAAzMwAAAD////4AAAYBgZiAAAAAAAAAMzMAAAA////+AAAYYgAAAAAAAAAzAMzMAAAAP//mZ4AAGGYAAAAAAAAAMwDMzAAAAD//5meAABgZgAAAAAAAAAzAMzMAAAAP+5mZgAAYGYAAAAAAAAAMwDMzAAAAB/mZmYAAGCAAAAAACAAAMzDMzwAAAAf/5meAABhgAAAAAAwAADMwzM8AAAAH/+ZngAA4mAAgAAAAAAAAADM/wAAAA7v4A8AAeZgAYAAAAAAAAAAzP8AAAAEZ+AHgAGZgAAAAgAgAwAAADP/wAQAERPwB4ABmYAAAAMAMAMAAAAz/8AMABGZ+AeAAeYAAIAAAAAAAAAA/MzAAABEBuABgAHmAAGAAAAAAAAAAPzMwAAATgZgAYADiAAB+IAgICAgAD8zMwEAAQEB8AHAB5gAAfiAMDAwMAA/MzMDAAMBgfgB4AZgACPwAAgAwADPzMzMxMRAAAb4AeAGYABn4AAMAMAAz8zMzMzMwAAGeAHgB4ggAGAAAiMCAAMzMT8/EQAAATgB4AeYYABgAAMzAwADMzM/PzMAAAGYAeAHAAAAAAAAAAAAAAAADg+AAAAAAAHgBmAYAAAAAMzMAAzMzAzPzAAABmYGYAcAAAAAAAAcAAAAAAAAD4AAAAAOAOAHmGYAYCMzPzDMADMAAD8wAAAZn/ngBwAAAAAAAHwAAAAAAAAOAAAAAA7g4B5hmAAAAAD8zAAAzMAADMwAAAZmZngfAAAAAAAA8AgAAIDgAA4AAAAAAAA4H4ZmAAIgAzMDAAMz8wA/MAAAABmYGB8AAAAAAAAAAAAAAOAAD4AAAAAAADgeeZmAAMwMAMAADMzMzM/AAAAAAGZ4H3mYgACICADAAAzMzMzPwAAAAABGeB/mZmAAIDAwMDADMz8zPzAAAAAZmZgf5mJgACAgICAwAzM/Mz+wAAAAERmYH5mBgAAAAAAAAAzM////wAAAAAAGeB+ZwIAAAAAAAAAMzP///8AAAAAABngZ5+ZgAAMAMAMzAzM///8wABAAGAGYGefmYAACACADMwMzP///sAAQADgBmBn5mZgAAAAAAAwAzM/8/8wAB4B4AHgZ+ZmIAAAAAAAMAMzP/P/sAA+AcAB4GefmZmAAADADMwMz//8z8wAf4YAAGBjn5nIgAAAgAzMDM///M/kAP+EAABgYf5n5iAAAAADMzMzM/M/8AHxmAAB4GH+Z+YgAAAAAzMzMzPzP/AB8RAAAeBmf/+ZgAAAAADMAMz8zM/MAEZgAAZgZn//yIAAAAAAzADM/MzPzABG4AAGYGGf/+YgAAAAAAMDPzMzM/8DEeAAAeBhn//mIAAAAAADAz8zMzP/ATngAAHgZn//mYgADMAAAADM/8zP/Mx/4AAGYGZ//4icAAzAAAAAzP/Mz/zM/+AABmAZmZ/mPgMzMAAAADPzMz//Ef/4AAGAGZmf9z4DMyAAAAAz8zM//xP/+AABgBhn5n+IjMzAAAAAzPzMz/zP/+YAB4AYZ+Z/3IzMwAAAAMz8zM/8z//kAAeAGZmZ//8zPzAAAAAz8zM/8xH/+AAZgBmZmf//Mz8wAAAAM/MzP/MR//gAGYAeZmZn+I/PwAAAAAzMz//8zH/mAH+AHmZmZ/yPz8AAAAAMzM///Mz/5gB/gBmf+Z//P/8wMMAAA/MzP/8T//mAGYAZn/mP/3//MDDAAAPzMz//Ef/5gBmAB+ZmZ////8zzMAAPzMz//8xGfmBmAAfmZmf////M8zAAD8zM///MRn5gZgAHmZ//////8zzAAAMzMzP/ERn5gZ4AB5mf//////M8wAADMzMz/xOR+YGeAAf+Zn//j8zM/zAAA8zMzPzPxn5mZgAH/mZ//4/MzP8wAAPMzMz8z8Z+ZmYAAfn5mf8zMAPPAAADMz8z//8Rn5mYAAH5+Zn/MzADzwAAAzM/M///ER+ZmAABnn5//4zAADMDAA/M/Mz//EZ+ZngAAZ5+f//MwAAzAwAPzPzM//5GfmZ4AAGZn5n//wAADwDAzzPzM///EZ/5mAABmZ+Z//8AAA8AwM8z8zP//xGf+ZgAAGf+ZmPzMAAzwzM8zPzPzPxGef/gAABn/mZn8zAAM8MzPMz8z8z8xnn/4AAAZ5n5//zMAM/ADM8z8zMzP/H//+AAAGeZ+f/8zADPwAzPM/MzMz/5///gAAAeZn//MzAAPwADP8/Mz8z///n/gAAAHmZ//zMwAD8AAz/PzM/M///5/4AAABmZ+fyMDMzPADz/P/M/M//+ZnmAAAAZmfn4jAzMzwA8/z/zPzP//mZ5gAAABmZ//zMzPz/A//zPzPzP/Ef55gAAAAZmf/8zMz8/wP/8z8z8z/xH+eYAAAAGGZ//jMzM///P/z8/8/8xH/5mAAAABhmf/4zMzP//z/8/P/P/ET/+ZgAAAAGGf38zMzM////8/////Mx/+ZgAAAABhn4/czMzP////P////zMf/mYAAAAAGGfnPzM/Mz/z/P/Pz8z8T/mYAAAAABhn4j8zPzM/8/z/z8/M/M/5mAAAAAAGGY/cz////////z//Mzv+ZmAAAAAABhmPzM////////8//zMz/mZgAAAAAAYmJyMzP///8//////MxPmZ4AAAAAAGZmIjMz////P/////zMTxmeAAAAAAAZmA/PzP///P////8zM//+eAAAAAAAGZgPz8z///z/////MzP//ngAAAAAAAYiJzP/8zMzP////8zM7/ngAAAAAAAGYiIz//MzMz/////MzE/54AAAAAAAAZiIyP///Mz/////MzM/4YAAAAAAAAGYjMz///zM/////zMzP8GAAAAAAAAAZiIz////Pz////zMzH+GAAAAAAAAAGYiM////z8////8zMx/BgAAAAAAAAAYCMzP///Mz///MzPz7hgAAAAAAAAAGAzMz///zM///zMz88wYAAAAAAAAAAOCMzM//zMzM/zMz8+xwAAAAAAAAAAHgjMzP/8zMzP8zM/PMcAAAAAAAAAAACDPzMz/z////zMz/EQAAAAAAAAAAAAgz8zM/8////8zM/xMAAAAAAAAAAAACDf///8////8zP+7EAAAAAAAAAAAAAwz////P////Mz/MzAAAAAAAAAAAAADif///////zM//sfAAAAAAAAAAAAAA8z///////8zP/zPwAAAAAAAAAAAAAA/c///P//Mz/87HgAAAAAAAAAAAAAAPzP//z//zM//MzwAAAAAAAAAAAAAAAf/////////zMfAAAAAAAAAAAAAAAAD/////////8zPwAAAAAAAAAAAAAAAAH8z/z////8z/gAAAAAAAAAAAAAAAAA/M/8/////M/wAAAAAAAAAAAAAAAAAAP/////8z/8AAAAAAAAAAAAAAAAAAAD//////M//AAAAAAAAAAAAAAAAAAAAB//zP///4AAAAAAAAAAAAAAAAAAAAAP/8z///8AAAAAAAAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=');
const MARS_SRC = bytes('AAAAAAAAAAAAAAAfgAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAH4AAAwAAAAAAAAAAAAAAAAAAAAAAAP+AAAOAAAAAAAAAAAAAAAAAAAAAAAf/gAAD4AAAAAAAAAAAAAAAAAAAAAAf/8AAAfgAAAAAAAAAAAAAAAAAAAAAPz/gAAD+AAAAAAAAAAAAAAAAAAAAAP4H4AAAf4AAAAAAAAAAAAAAAAAAAAHwHwAAAAeAAAAAAAAAAAAAAAAAAAAH4H4AAAADgAAAAAAAAAAAAAAAAAAAB+H8AAAAB4AAAAAAAAAAAAAAAAAAAAf/8AB/4B+AAAAAAAAAAAAAAAAAAAAH/8B///AYAAAAAAAAAAAAAAAAAAAAA/8A///4AAAAAAAAAAAAAAAAAAAAAAOAB//4f/gAAAADAAAAAAAAAAAAAAADgB/j/D/4AAAAAwAAAAAAAAAAAAAAAAD/g///+AAAAAMAAAAAAAAAAAAAAAAD/AAf/4AAAAADgAAAAAAAAAAAAAAAH/gAH/+AAAAAA+4AAAAAAAAAAAAAAD/AAAA8AAAAAABuAAAAAAAAAAAAAAB/AAAAHAAAAAAADgQAAAAAAAAAAAAB+AAAADwAAAAAAAAOAAAAAAAAAAAAA/AAABg8AAAAAAAADwAAAAAAAAAAAA/4BwAd/PAAAAAAAA4AAAAAAAAAAAAfuG8AH/DwAAAAAAAAAAAAAAAAAAAAP3n/AB/v8AAAAAAHAAAAAAAAAAAAADxx3AA/nwAAAAAAB/4AAAAAAAAAAAA4e8AAfv4AAAAAAAf+AAAAAAAAAAAAODuAAfH8AAAAAAAAAAAAAAAAAAAAADh7gB//+AAAAAAAAAAAAAAAAAAAAAA4ecP//+AAAAAAAAAAAAAAAAAAAAAAPHnf/B4AAAAAAAAAAAAAAAAAAAAAADx//+B/gAAAAAAAAAABgAAAAAH+AAB4P/wA/4AAAAAAAAAAAcAAAAAB//AAcB/gB/OAAAAAAAAAAADgAAAAAAP8AHAAAD/gAAAAAAAAAAAAAAAAAAAAfgBgwAH/8AAAAAAAAAAAABAAAAAAAB+AAO/h/3AAAAAAAAAAAAAYAAAAAYAHwADv+ABwAAAAAAAAAAAACAAAAAH4AeAA77gAMAAAAAAAAAAAAAwAAAAA+ADgAMA4AAAAAAAAAAAAAAAAAAAAAD5/4ADAOAAAAAAAAH/z/AAAHAAAAAAPf+AAAAAAAAAAAAP/8/+AAB8AAAAAB7/AAAAAAAAAAAAP/AAfgAAbAAAAGAOeAAAAAHAAAAAB/+AAB+AAA4AAABwBjwAAAABwAAAAAfgAAADwAAHAAAAeAccAAAAf8AAAAAHAAAAAeAABwAAADwDDgAAAf+AAAAABwAAAADgeACAAAAcA44AAB/8AAAAAAfwAAAAcf4AgAAADAOHAAB/AAAAAAAD/AAAADneAMAAAA4DhwAA/AAAAAAAAP+AAAA5zgDAAAAGA4cAA/AAAAAAAAA/8AAAOc+AwAAABwOHAAeAAAAAAAAAAPgAADnHgAAAAAcDjwAfAAAAAAAAAAB8AAA5w4AAAAAHBw4APAAAAAAAAAAAHAAAOeGAAAAABwccAHgAAAAAAAAAAfgAADjzgAABAAYYfADwAAAAAAAAAAfwAAAwe4AAAQAGOHgA4AAAAAAAAAA/wAAAMH+AAAAADjnwAcAAAAAAAAAAPgAAAHA/gAAAABwxwAHAAAAAAAAAAAAAAADgDgAAAAAcAAABwAAAAAAB4AAAAAAA4AAAAAAAPAAAAYAAAAAAAeAAAAAAAMAAAAAAAHgAAAHAAAAAAAHwAAAAAAOAMAAOAADwAAABwAAAAAAAP8fgAAADgDAADgABwAAAAcAAAAAAAD/H+AAAAwHwAA4AA8AAAAHAAAAAAAAAADgAADgHwAAOAA+AAAAAwAAAAAAAAAA4AAB4BwAADgA/AAAAAOAAAAAAAAAAOAAH8AcAAH4AfAAAAABwAAAAAAAAAHAAH8AHAAH4A/gAAAAAcAAAAAAAAAHwAP8AB+AH8APgAAAAADgAAAAAAAAD4AHwAAHgD4AD4AAAAAA+AAAAAAAAD8AD4AAAYB8AAeAAAAAAHgAAAAAAAB8AA4AAAeA8AADgAAAAAA+AAAAAAAA+AAOAAAHgPAAB4AAAAAAH/AAAAAAB/AADwAA/wD4AB8AAAAAAAfwAAAAAA/AAAfAA/wAfgAf+AAAAAAB8AAAAAH/AAAD/H/wAB/+Af4AAAAAAAAAAAAP+AAAAHx+AAAH/gA/gAAAAAAAAAAP/+AAAAAAAAAAAAAAB8AAAAAAAA4P//wAAAAAAAAAAAAAAAHgAAAAAAAP///AAAAAAAAAAAAAAAAB8AAAAAAAD//4AAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAf4AAAAAABgAAMAAAAAAAAAAAAAAAP3/8AAAAAA4AAHAAAAAAAAAAAAAAH/9//8AAAAAOAADwAAAAAAAAAAAAAP/gAAfwAAAADAAB4AAAAAAAAAAAAAf8AAAB+AAAAA4AH8AAAAAAAAAAAAB/8AAAAHwAAAAPAD8AAAAAAAAAAAAB/AAAAAAOAAAAAwA8AAAAAAAAAAAAD/AAAAAADgAAAAEAAAAAAAAAAAAAAB+AAAAAAA4AAAAAADgAAAAAAAAAAAB8AAAAAAAOAAAAAAB8AAAAAAAAAAAB8AAAAAAAHAAAAAAA/gAAAAAAAAAAA+AAAAAAADwAAAAAAf8AAAAAAAAAAAfAAAAAAAB4AAAADgHPAAAAAAAAAAAPAAAAAAAAcAAAAA4BxwAAAAAAAAAADgAAAAAAAGAAAAAMAYcAAAAAAAAAAAwAAAAAAAMAAAAAAAHPAAAAAAAAAAAOAAAAAAADAAAAAAABzwAAAAB/gAAADgAAAAAAAwAAAwAAAf8AAAA4f4cAAA/AAAAAAAOAADMAAAD+AAAPuH+H8AAHz+AYAAAD4HwzAAAAeAAAP4AAAPAAAA/gHAAAAOB8AAAAAABwAD+AAAAwAAAAABwAAAAAAAAAAAAAfAAHgAAAGAAAAAA8AAAAAAAAAAAAAH///4AAA/gAAAAAeAAAAAAAAAAAAAAD//wAAP/wAAAAAHAAAAAAAAAAAAAAAD/AAA//wAAAAAAAAAAAAAAAAAAAAAAAAAf/gAAAAAAAAAAAAAAAAAAAAAAAAAAf+AAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAwAAAAAAA+AAAAAAAAAAAAAAAAAAAB8AwAAAAAH4AAAAAAAD8AAAAAAAAAA+AHgAAAAAf8AAAAB///AAAAAAAAAB/gB+AAAAAB/8AAD///4AAAAAAAAAA/AAP4AAAAAH//////8AAAAAAAAAAA/AAA/8AAAAAP/////AAAAAAAAAAAB/gAAA/wAAAAAAAAAAAAAAAAAAAAAA/AAAAD/wAAAAAAAAAAAAAAAAAAAAD/AAAAOD/gAAAAAAAAAAAAAAAAAAAB+AAAAD/H+AAAAAAAAAAAAAAAAAAAH+ABgAAP8H4AAAAAAAAAAAAAAAAAAH8AHwAAA/4eAAAAAAAAAAAAAAAAAAP8B/8AAAD//gAAGAAAAAAAAAAAAAAD8f/+AAAAAfwAABgAAAAAAAAAAAAAA/H4DgAAAAAAAAH/gAAAAAAAAAAAAAPwAAwAAAAAAAAH/4AAAAAAAf/n8AAAAABwAAAAAAAAB//4MAAAfAH///P8AAAAcAAAAAAAAAb++HAAAHwAHfgD/cAAD4AAAAAAAAOB/wBwAAAAAH38AB3wAB+AAAAAAAADz//+YAAAAAN8HwAB+AA/wAAAAAAAAd+D/wAAAAADAA/AAB4AecAAAAAAAAH/cf+eAAAAAAADwAAOAPnAAAAAAAABvHAH3wAAAAAAAcAADgHjgAAAAAAAAbxwA8+ADgAAAAHAAA4Bw4AAAAAAAAG4YAHjgA4AAAABwAAAAccAAAAAHAAB/GAB84AOAAAAAYADAAHOAAAAAB7gAfxwAPuADnA8A4AAPwAB/gAAAAAe4AH8cAA98ABwPAOAADwAAfwAAAAAH+AA8HAAPHAAADwAAAD/AAD4AAAAAAPgAPwAABwAAAAAAAAA/3gAAAAAAAAB/AB+AAHMAAAAAAAAAB9/wAAAAAAAAD8APwAD3AAAAAAAAAAAD/AAAAAAAAAfwB+AA9zAAAAAAAAAAAHwAAAAAAAAB/gPwAP98AAAAAAAAAAA/AAAAAAAAAB8A8AA+/AAAAAAAAAAABwAAAAAAAAAHgH4AP/AAAAAAAAAAAAcAAAAAAAAAA4B/gA/gAAAAAAAAAAAHAAAAAAAAAAeAP/5/wAAAAAAAAAAADgAAAAAAAAAfAAf//gAAAAAAAAAAADwAAAAAAAAAfgAA//wAAAAAAAAAAAB4AAAAAAAAAPAAAAPAAAAAAAAAAAAH8AAAAAAAAAA+AAAAAAAAAAAAAAAAH8AAAAAAAAAAH/gAAAAAAAAAAAAAA/8AAAAAAAAAAAP8AAAAAAAAAAAAAAPwAAAAAAAAAAAAf4AAADgAAAAAAAADAAAAAAAAAAAAAA/AAAA4OAAAAAAAAAAAAAAAAAAAAAAD4D+AP/gAAAAAAAAAAAAAAAAAAAAAAPA/w//8AAAAAAAAAAAAAAAAAAAAAABwP+P//uAAAAAAAAAAAAAAAAAAAAAAcD3z///gAAAAAAAAAAAAAAAAAAAAAHA8ceAHwAAAAAAAAAAAAAAAAAAAAABwP/H4A/AAAAAAAAAAAAAAAAAAAAAAAA/w/ADwAAAAAAAAAAAAAAAAAAAAAAAH4H/B8AAAAAAAAAAAAAAAAAAAAAAAAAAf//AAAAAAAAAAAAAAAAAAAAAAAAAAB//gAAAAAAAAAAAAAAAAAAAAAAAAAAH/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=');
function bytes(b64) { return Uint8Array.from(atob(b64), c => c.charCodeAt(0)); }
const PLACES = [['moon', 'Moon'], ['mars', 'Mars'], ['earth', 'Earth'], ['jupiter', 'Jupiter']];
const POSES = ['rest', 'stand', 'wave', 'dance', 'swim', 'point', 'pushup', 'bow',
  'cute', 'freaky', 'worm', 'shake', 'shrug', 'dead', 'crab'];
const state = { command: '', face: '', settings: {} };
const $ = id => document.getElementById(id);
const isPlanet = cmd => PLACES.some(p => p[0] === cmd);
const ROBOT = location.protocol === 'file:' ? 'http://192.168.4.1' : '';
function robotPath(name, value) {
  switch (name) {
    case 'go':      return '/cmd?go=' + encodeURIComponent(value);
    case 'pose':    return '/cmd?pose=' + encodeURIComponent(value);
    case 'stop':    return '/cmd?stop=1';
    case 'setting': return '/setSettings?' + encodeURIComponent(value.key) + '=' + encodeURIComponent(value.value);
  }
  return null;
}
function setLink(ok) { $('link').hidden = ok; }
function request(path) {
  const ctl = new AbortController(), t = setTimeout(() => ctl.abort(), 4000);
  return fetch(ROBOT + path, { signal: ctl.signal })
    .then(r => { if (!r.ok) throw new Error('HTTP ' + r.status); setLink(true); return r; })
    .catch(e => { setLink(false); throw e; })
    .finally(() => clearTimeout(t));
}
let queue = Promise.resolve();
let localUntil = 0;
function sendCommand(name, value) {
  switch (name) {
    case 'go': case 'pose': state.command = value; break;
    case 'stop': state.command = ''; break;
    case 'setting': state.settings[value.key] = value.value; break;
  }
  localUntil = performance.now() + 1500;
  markPlace();
  const path = robotPath(name, value);
  if (!path) return;
  const tries = name === 'stop' ? 3 : 1;
  const attempt = n => request(path).catch(e => { if (n > 1) return attempt(n - 1); throw e; });
  queue = queue.then(() => attempt(tries)).catch(() => {
    if (name === 'pose' || name === 'go') { state.command = ''; markPlace(); }
  });
}
function pollStatus() {
  request('/api/status').then(r => r.json()).then(s => {
    if (performance.now() < localUntil) return;
    state.command = s.currentCommand || '';
    state.face = s.currentFace || '';
    markPlace();
  }).catch(() => {}).finally(() => setTimeout(pollStatus, 1000));
}
const ctx = $('screen').getContext('2d');
const img = ctx.createImageData(128, 64);
const lit = new Uint8Array(128 * 64);
function flush() {
  for (let p = 0; p < 128 * 64; p++) img.data.set(lit[p] ? [235, 235, 235, 255] : [0, 0, 0, 255], p * 4);
  ctx.putImageData(img, 0, 0);
}
flush();
function showFace(name) {
  const bits = bytes(FACES[name]);
  for (let p = 0; p < 128 * 64; p++) lit[p] = bits[p >> 3] & (0x80 >> (p & 7)) ? 1 : 0;
  flush();
}
const PI = Math.PI, DEG = 0.0174533;
const FRAME_MS = 70, SPIN_STEP = 0.08;
const BAYER4 = [[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]];
const JUP_BANDS = [[62, 1], [50, 2], [40, 1], [31, 2], [24, 1], [17, 3], [7, 0], [-7, 3],
  [-20, 0], [-27, 3], [-35, 1], [-45, 2], [-58, 1], [-68, 2], [-91, 1]];
function wrapPi(a) {
  while (a > PI) a -= 2 * PI;
  while (a < -PI) a += 2 * PI;
  return a;
}
function texel(type, sx, sy, lat, lon) {
  if (type === 'earth') {
    let col = Math.trunc((lon / (2 * PI) + 0.5) * 128);
    col = ((col % 128) + 128) % 128;
    const row = Math.max(0, Math.min(63, Math.trunc((0.5 - lat / PI) * 64)));
    return EARTH_MAP[row * 16 + (col >> 3)] & (0x80 >> (col & 7));
  }
  if (type === 'mars' || type === 'moon') {
    let L = wrapPi(lon);
    if (L > PI / 2) L = PI - L;
    else if (L < -PI / 2) L = -PI - L;
    const scale = type === 'mars' ? 87 : 84;
    const u = Math.trunc(88 + Math.cos(lat) * Math.sin(L) * scale + 0.5);
    const v = Math.trunc(88 - Math.sin(lat) * scale + 0.5);
    const src = type === 'mars' ? MARS_SRC : MOON_SRC;
    let n = 0;
    for (let dy = -1; dy <= 1; dy++) {
      for (let dx = -1; dx <= 1; dx++) {
        const xx = u + dx, yy = v + dy;
        if (xx < 0 || xx > 175 || yy < 0 || yy > 175) continue;
        if (src[yy * 22 + (xx >> 3)] & (0x80 >> (xx & 7))) n++;
      }
    }
    if (type === 'mars') return n >= 2;
    const g = (n / 9 - 0.22) / 0.56;
    return g > (BAYER4[sy & 3][sx & 3] + 0.5) / 16;
  }
  const L = wrapPi(lon);
  const dl = wrapPi(L - 1.0) * Math.cos(lat) / 0.30;
  const dt = (lat + 22 * DEG) / 0.15;
  const e = dl * dl + dt * dt;
  if (e < 0.35) return true;
  if (e < 1.0) return false;
  if (e < 1.8) return true;
  const d = lat / DEG + 2.2 * Math.sin(L * 4 + lat * 2) + 1.2 * Math.sin(L * 9);
  let level = JUP_BANDS[JUP_BANDS.length - 1][1];
  for (const [edge, bright] of JUP_BANDS) {
    if (d > edge) { level = bright; break; }
  }
  return level >= 2;
}
function showPlanet(type, spin) {
  const cx = 64, cy = 32, r = 30;
  lit.fill(0);
  for (let py = -r - 1; py <= r + 1; py++) {
    for (let px = -r - 1; px <= r + 1; px++) {
      const x = px / r, y = py / r, d2 = x * x + y * y;
      let on = false;
      if (d2 <= 1) {
        const z = Math.sqrt(1 - d2);
        on = texel(type, cx + px, cy + py, Math.asin(-y), Math.atan2(x, z) - spin);
      } else if (type !== 'moon') {
        on = Math.round(Math.hypot(px, py)) === r + 1;
      }
      if (on) lit[(cy + py) * 128 + cx + px] = 1;
    }
  }
  flush();
}
let spin = 0, drawn = '';
setInterval(() => {
  if (isPlanet(state.command)) {
    if (drawn !== state.command) { drawn = state.command; spin = 0; }
    showPlanet(state.command, spin);
    spin += SPIN_STEP;
    if (spin > 2 * PI) spin -= 2 * PI;
    return;
  }
  const face = state.face === 'idle_blink' ? 'idle' : state.face;
  if (FACES[face] && drawn !== 'face:' + face) { drawn = 'face:' + face; showFace(face); }
}, FRAME_MS);
function markPlace() {
  document.querySelectorAll('#places button').forEach(b => b.classList.toggle('on', b.dataset.cmd === state.command));
}
PLACES.forEach(([cmd, name]) => {
  const b = document.createElement('button');
  b.dataset.cmd = cmd;
  b.textContent = name;
  b.onclick = () => sendCommand('pose', cmd);
  $('places').appendChild(b);
});
POSES.forEach(n => {
  const b = document.createElement('button');
  b.textContent = n;
  b.onclick = () => sendCommand('pose', n);
  $('poses').appendChild(b);
});
let held = null;
function releaseDrive() {
  if (!held) return;
  held = null;
  sendCommand('stop');
}
document.querySelectorAll('[data-go]').forEach(b => {
  b.addEventListener('pointerdown', e => {
    e.preventDefault();
    try { b.setPointerCapture(e.pointerId); } catch (err) {}
    held = b;
    sendCommand('go', b.dataset.go);
  });
  ['pointerup', 'pointercancel', 'lostpointercapture'].forEach(type => b.addEventListener(type, releaseDrive));
  b.addEventListener('contextmenu', e => e.preventDefault());
});
addEventListener('blur', releaseDrive);
addEventListener('pagehide', releaseDrive);
document.addEventListener('visibilitychange', () => { if (document.hidden) releaseDrive(); });
document.querySelectorAll('[data-stop], #halt').forEach(b => { b.onclick = () => sendCommand('stop'); });
const STEPS = {};
document.querySelectorAll('.step').forEach(el => {
  const key = el.dataset.key, min = +el.dataset.min, max = +el.dataset.max, inc = +(el.dataset.inc || 1);
  const out = el.querySelector('output');
  let v = parseInt(out.textContent, 10), wait = null;
  const [less, more] = el.querySelectorAll('button');
  const show = n => { v = Math.max(min, Math.min(max, n)); out.textContent = v; };
  const bump = dir => {
    show(v + dir * inc);
    clearTimeout(wait);
    wait = setTimeout(() => sendCommand('setting', { key, value: v }), 300);
  };
  less.onclick = () => bump(-1);
  more.onclick = () => bump(1);
  STEPS[key] = show;
});
request('/getSettings').then(r => r.json()).then(s => {
  Object.keys(s).forEach(k => { if (STEPS[k]) STEPS[k](s[k]); });
}).catch(() => {});
const JOINTS = ['R1', 'R2', 'L1', 'L2', 'R4', 'R3', 'L3', 'L4'];
const JOINT_PART = { R1: 'hip', R2: 'hip', L1: 'hip', L2: 'hip', R3: 'leg', R4: 'leg', L3: 'leg', L4: 'leg' };
['calib-joint', 'debug-joint'].forEach(id =>
  JOINTS.forEach(j => $(id).add(new Option(j + ' (' + JOINT_PART[j] + ')', j))));
let calib = null;
function showCalib(note) {
  const line = id => {
    const i = JOINTS.indexOf($(id + '-joint').value);
    if (!calib) return '';
    const raw = calib.raw[i] < 0 ? 'not moved yet' : calib.raw[i];
    return 'Angle: ' + raw + '. Min ' + calib.min[i] + ', max ' + calib.max[i] +
      ', centre ' + (90 + calib.trim[i]) + '. Direction: ' + (calib.rev[i] ? 'reversed' : 'normal') + '.';
  };
  $('calib-info').textContent = (note ? note + ' ' : '') + (line('calib') || 'Press Start.');
  $('debug-info').textContent = line('debug');
}
function calibRequest(path, done) {
  queue = queue.then(() => {
    const ctl = new AbortController(), t = setTimeout(() => ctl.abort(), 8000);
    return fetch(ROBOT + path, { signal: ctl.signal })
      .then(r => r.ok ? r.json().then(j => { calib = j; setLink(true); showCalib(done); })
                      : r.text().then(msg => { setLink(true); showCalib(msg + '.'); }))
      .catch(() => { setLink(false); showCalib('No answer from the robot.'); })
      .finally(() => clearTimeout(t));
  });
}
$('calib-start').onclick = () => calibRequest('/api/calib/start', 'All joints at the middle.');
document.querySelectorAll('[data-calib-jog]').forEach(b => {
  b.onclick = () => calibRequest('/api/jog?raw=1&motor=' + $('calib-joint').value + '&delta=' + b.dataset.calibJog);
});
document.querySelectorAll('[data-calib-set]').forEach(b => {
  b.onclick = () => calibRequest('/api/calib/set?motor=' + $('calib-joint').value + '&what=' + b.dataset.calibSet, 'Saved.');
});
$('calib-reset').onclick = () => calibRequest('/api/calib/reset?motor=' + $('calib-joint').value, 'Reset.');
$('calib-reverse-all').onclick = () => calibRequest('/api/calib/set?motor=all&what=reverse', 'Saved.');
document.querySelectorAll('[data-debug-jog]').forEach(b => {
  b.onclick = () => calibRequest('/api/jog?motor=' + $('debug-joint').value + '&delta=' + b.dataset.debugJog);
});
$('calib-joint').onchange = $('debug-joint').onchange = () => showCalib();
['calib', 'debug'].forEach(id => $(id).addEventListener('toggle', () => { if ($(id).open) calibRequest('/api/calib'); }));
$('classic').href = ROBOT + '/classic';
pollStatus();
</script>
</body>
</html>)nova_panel";
#endif
